version: '3.8'

services:
  narayandb:
    image: mysql:8.0
    container_name: narayandbc1
    environment:
      MYSQL_ROOT_PASSWORD: Hello@12345
      MYSQL_DATABASE: ashutestdb

  Narayanwebflaskapp:
    image: narayanflask:webappv1
    build: .
    ports:
      - "3031:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: narayandb # db server name
      MYSQL_USER: root #db user name
      MYSQL_PASSWORD: example # db password
      MYSQL_DATABASE: testdb
    depends_on:
      - narayandb

volumes:
  mysql_data:
  