version: '3.9'
services:
  narayanspringboot:
    image: narayanspring:tomcatv1  # if this image is not present then only it will build
    build:
      context: .  # location of dockerfile
      dockerfile:  Dockerfile # name of dockerfile
    container_name: NarayanC3
    ports:
    - 3034:8080  
# above steps have merging of build and run